/// Flutter icons Clothicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Clothicons
///      fonts:
///       - asset: fonts/Clothicons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Clothicons {
  Clothicons._();

  static const _kFontFam = 'Clothicons';
  static const _kFontPkg = null;

  static const IconData sport_trousers_pants =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wedding_dress =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman_shirt =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fashion_purse =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panties =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
